<?php

define ("PRIV_ADMINACC_VIEW", "adminacc_view");
define ("PRIV_ADMINACC_EDIT", "adminacc_edit");
define ("PRIV_ADMINACC_DELETE", "adminacc_delete");
define ("PRIV_APT_VIEW", "apt_view");
define ("PRIV_APT_EDIT", "apt_edit");
define ("PRIV_APT_DELETE", "apt_delete");
define ("PRIV_STANZE_VIEW", "stanze_view");
define ("PRIV_STANZE_BOOKING", "stanze_booking");
define ("PRIV_STANZE_EDIT", "stanze_edit");
define ("PRIV_STANZE_DELETE", "stanze_delete");
define ("PRIV_INQUILINI_VIEW", "inq_view");
define ("PRIV_INQUILINI_EDIT", "inq_edit");
define ("PRIV_INQUILINI_DELETE", "inq_delete");
define ("PRIV_CLIENTI_VIEW", "cli_view");
define ("PRIV_CLIENTI_EDIT", "cli_edit");
define ("PRIV_CLIENTI_DELETE", "cli_delete");
define ("PRIV_PAGE_VIEW", "page_view");
define ("PRIV_PAGE_EDIT", "page_edit");
define ("PRIV_ZONE_VIEW", "zone_view");
define ("PRIV_ZONE_EDIT", "zone_edit");
define ("PRIV_ZONE_DELETE", "zone_delete");
define ("PRIV_RICHIEDENTI_VIEW", "rich_view");
define ("PRIV_RICHIEDENTI_EDIT", "rich_edit");
define ("PRIV_RICHIEDENTI_DELETE", "rich_delete");
define ("PRIV_POSTIAUTO_VIEW", "postiauto_view");
define ("PRIV_POSTIAUTO_EDIT", "postiauto_edit");
define ("PRIV_POSTIAUTO_DELETE", "postiauto_delete");
define ("PRIV_TRANSAZIONI_VIEW", "trans_view");
define ("PRIV_TRANSAZIONI_EDIT", "trans_edit");
define ("PRIV_TRANSAZIONI_DELETE", "trans_delete");
define ("PRIV_FATTURAZIONE_VIEW","invoice_view");
define ("PRIV_FATTURAZIONE_ADD","invoice_add");
define ("PRIV_FATTURAZIONE_EDIT","invoice_edit");
define ("PRIV_FATTURAZIONE_DOWNLOAD","invoice_download");
define ("PRIV_FATTURAZIONE_DELETE","invoice_delete");
define ("PRIV_TRANSAZIONI_DATAENTRY","trans_dataEntry");
define ("PRIV_TRANSAZIONI_CONTABILE","trans_contabile");
define ("PRIV_TRANSAZIONI_COMMERCIALISTA","trans_commercialista");
define ("PRIV_CHECKINCHECKOUT","checkin_checkout");
define ("PRIV_ITT_READ","itt_read");
define ("PRIV_RECUPERO_CREDITI","recupero_crediti");
define("PRIV_TICKET_OPEN", "ticket_open");
define ("PRIV_TICKET_FORNITORE", "ticket_fornitore");
define("PRIV_DOVEVIVO", "dovevivo");
